server:
  port: 8080
  servlet:
    context-path: /hm
spring:
  application:
    name: HMoneta
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.101:3306/home_lab_server?useUnicode=true&characterEncoding=UTF-8
    hikari:
      username: homelab
      password: HomeLab215178^&%@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  task:
    scheduling:
      pool:
        size: 1

logging:
  level:
    sql: info

hmoneta:
  version: @project.version@
  master:
    report-url: http://127.0.0.1
  agent:
    port: 477


