server:
  port: 8080
spring:
  application:
    name: HMoneta
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://xx.xx.xx.xx:5432/databaseName
    username: username
    password: password

    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariPool-HMoneta
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  task:
    scheduling:
      pool:
        size: 1

logging:
  level:
    sql: info

hmoneta:
  version: @project.version@
  master:
    report-url: serviceIp
  agent:
    port: 477
    report-delay: 60000


