server:
  port: 8080
spring:
  application:
    name: HMoneta
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.5.20.103:5432/home_lab_server_test?useUnicode=true&characterEncoding=UTF-8
    hikari:
      username: jack
      password: labixiaoxin93712
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  task:
    scheduling:
      pool:
        size: 1

logging:
  level:
    sql: info

hmoneta:
  version: @project.version@
  master:
    report-url: http://127.0.0.1
  agent:
    port: 477
    report-delay: 60000


