###
// 新增IpPool
POST localhost:8080/pool/modify
Content-Type: application/json

{
  "poolId": "",
  "poolName": "Test",
  "networkAddress": "192.168.1.0",
  "mask": "/24",
  "startAddr": "192.168.1.1",
  "endAddr": "192.168.1.50",
  "create": true
}

###
//查询SelectValue
GET localhost:8080/pool/selectValue

###
@isRandom = true
@poolId = 1783414960022491136
//获取ip地址
GET http://localhost:8080/pool/generate?
    poolId={{poolId}}&
    isRandom={{isRandom}}